services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - API_URL=http://api:5050
    depends_on:
      - api
    networks:
      - todo-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=todouser
      - MYSQL_PASSWORD=todopassword
      - MYSQL_DB=tododb
      - SECRET_KEY=your_secure_secret_key
      - MOCK_TRANSLATE=false
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-creds.json
    volumes:
      - ./trusty-shine-453002-b9-b9ba8ba27281.json:/app/google-creds.json
    ports:
      - "5050:5001"
    depends_on:
      - mysql
    networks:
      - todo-network
    restart: unless-stopped
    command: ["python", "api_backend_mysql.py"]

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tododb
      - MYSQL_USER=todouser
      - MYSQL_PASSWORD=todopassword
    ports:
      - "3308:3306"
    networks:
      - todo-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
