apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  secret-key: eW91cl9zZWN1cmVfc2VjcmV0X2tleQ== 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: gcr.io/trusty-shine-453002-b9/todolist-api:latest
        ports:
        - containerPort: 5050
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: todouser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user-password
        - name: MYSQL_DB
          value: tododb
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: secret-key
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/google-creds/google-credentials.json
        volumeMounts:
        - name: google-creds
          mountPath: /app/google-creds
          readOnly: true
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: google-creds
        secret:
          secretName: google-translate-creds
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  selector:
    app: todo-api
  ports:
  - port: 5050      
    targetPort: 5050    
  type: ClusterIP