apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  secret-key: eW91cl9zZWN1cmVfc2VjcmV0X2tleQ==  # your_secure_secret_key (base64 encoded)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: ${DOCKER_REGISTRY}/todo-api:latest  # Replace with your actual image
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: todouser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user-password
        - name: MYSQL_DB
          value: tododb
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: secret-key
        volumeMounts:
        - name: google-creds
          mountPath: /app/google-credentials.json
          subPath: google-credentials.json
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: google-creds
        secret:
          secretName: google-translate-creds
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  selector:
    app: todo-api
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP